export const THEME = {
  themeName: "EUI_THEME_AMSTERDAM",
  colors: {
    ghost: "#FFF",
    ink: "#000",
    primary: "#3a86ff",
    accent: "#F04E98",
    success: "#00BFB3",
    warning: "#FEC514",
    danger: "#F32013",
    emptyShade: "#FFF",
    lightestShade: "#f0f4fb",
    lightShade: "#D3DAE6",
    mediumShade: "#98A2B3",
    darkShade: "#69707D",
    darkestShade: "#343741",
    fullShade: "#000",
    body: "#f8fafd",
    highlight: "#fff9e8",
    disabled: "#ABB4C4",
    disabledText: "#a2abba",
    shadow: "#000",
    primaryText: "#3a86ff",
    accentText: "#c4407c",
    successText: "#007e77",
    warningText: "#8a6a0a",
    dangerText: "#F32013",
    text: "#343741",
    title: "#1a1c21",
    subdued: "#69707d",
    link: "#3a86ff",
  },
  base: 16,
  size: {
    xxs: "2px",
    xs: "4px",
    s: "8px",
    m: "12px",
    base: "16px",
    l: "24px",
    xl: "32px",
    xxl: "40px",
    xxxl: "48px",
    xxxxl: "64px",
  },
  font: {
    family: "'Manrope', BlinkMacSystemFont, Helvetica, Arial, sans-serif",
    familyCode: "'Manrope', Menlo, Courier, monospace",
    featureSettings: "'calt' 1, 'kern' 1, 'liga' 1",
    baseline: 4,
    lineHeightMultiplier: 1.5,
    scale: {
      xxxs: 0.5625,
      xxs: 0.6875,
      xs: 0.75,
      s: 0.875,
      m: 1,
      l: 1.25,
      xl: 1.75,
      xxl: 2.125,
    },
    weight: {
      light: 300,
      regular: 400,
      medium: 500,
      semiBold: 600,
      bold: 700,
    },
    body: {
      scale: "s",
      weight: "regular",
    },
    __docgenInfo: {
      filePath:
        "/Users/constance/Documents/eui/src/themes/amsterdam/global_styling/variables/_typography.ts",
      description:
        "Amsterdam theme just changes the main font from the beta Inter UI to Inter",
      displayName: "font_ams",
      methods: [],
      extendedInterfaces: [],
    },
  },
  border: {
    color: "#D3DAE6",
    width: {
      thin: "1px",
      thick: "2px",
    },
    radius: {
      medium: "6px",
      small: "4px",
    },
    thin: "1px solid #D3DAE6",
    thick: "2px solid #D3DAE6",
    editable: "2px dotted #D3DAE6",
  },
  animation: {
    extraFast: "90ms",
    fast: "150ms",
    normal: "250ms",
    slow: "350ms",
    extraSlow: "500ms",
    bounce: "cubic-bezier(.34, 1.61, .7, 1)",
    resistance: "cubic-bezier(.694, .0482, .335, 1)",
  },
  breakpoint: {
    xl: 1200,
    l: 992,
    m: 768,
    s: 575,
    xs: 0,
  },
};
